/**
 * Generates the program_sessions seed from content/programs, so the table and
 * the copy can never drift apart. Re-run after editing a track:
 *
 *   npm run gen:sessions
 */
import fs from "node:fs";
import { PROGRAMS } from "../content/programs";

const esc = (s: string) => s.replace(/'/g, "''");

const rows = PROGRAMS.flatMap((p) =>
  p.sessions.map(
    (s) =>
      `  ('${p.id}', ${s.day}, '${s.kind}', ${s.minutes}, '${esc(s.title)}', '${esc(s.ref)}')`
  )
);

const sql = `-- GENERATED by scripts/gen-sessions-sql.ts — do not edit by hand.
-- Structure only; the words live in content/programs, keyed by content_ref.

delete from public.program_sessions;

insert into public.program_sessions (program_id, day_index, kind, minutes, title, content_ref) values
${rows.join(",\n")};
`;

fs.writeFileSync("supabase/migrations/20260201000001_seed_sessions.sql", sql);
console.log(`wrote ${rows.length} sessions`);
